### ISSUE TITLE
It shows "False" instead of "No"

### ISSUE THREAD

**Issue by vi** [inducer/relate#136]
```
 - id: multipr
   prompt: "# Is it any good?"
   value: 2
   type: ChoiceQuestion
   choices:
    - ~CORRECT~ Yes
    - No
```

![q](http://s27.postimg.org/yo51tcolb/image.jpg?noCache=1449251333)
