### ISSUE TITLE
Sandbox Errors

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#186]
It raises ScannerError: mapping values are not allowed here in "", line 2, column 11: id: eigvec ^

The testing code is from [sample](https://github.com/inducer/relate-sample/blob/master/flows/quiz-test.yml)
```
        type: TextQuestion
        id: eigvec
        value: 2
        prompt: |
            # What's an eigenvector?
            Yadda ___________________ yadda.
        answers:

          - <plain>matrix
          - <case_sens_plain>Eigenmatrix
          - <regex>(?:linear\s+)?\s*map
          - <case_sens_regex>(?:operator\s+)?\s*map

```
