### ISSUE TITLE
``markup_to_html`` failed in inline question in some cases

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#330]
Uing the [demo course repo](https://github.com/inducer/relate-sample), with the following question (in sandbox)

```
        type: InlineMultiQuestion
        id: inlinemulti
        value: 10
        prompt: |
            # An InlineMultiQuestion example
            Complete the following paragraph.
        question: |

            <img src="repo:images/classroom.jpeg">
            Foo and [[blank1]] are often used in code examples, or
            tutorials. $\frac{1}{5}$ is equivalent to [[blank_2]].
            The correct answer for this choice question is [[choice_a]].
            The Upper case of "foo" is [[choice2]].
            One dollar is [[blank3]], and five percent is [[blank4]], and "Bar"
            wrapped by a pair of parentheses is [[blank5]].
        answers:

            blank1:
                type: ShortAnswer
                width: 4em
                required: True
                hint: Tex can be rendered in hint, e.g. $x_1$.
                hint_title: Hint
                correct_answer:
                - <plain> BAR
                - <plain>bar

            blank_2:
                type: ShortAnswer
                width: 10em
                hint: <ol><li>with no hint title</li><li>HTML is OK</li><ol>
                correct_answer:
                - <plain> "1/5"
                - type: float
                  value: 1/5
                  rtol: 0.00001
                - <plain> 0.2

            choice_a:
                type: ChoicesAnswer
                required: True
                choices:
                - ~CORRECT~ Correct
                - Wrong

            choice2:
                type: ChoicesAnswer
                choices:
                - ~CORRECT~ FOO
                - BAR
                - fOO

            blank3:
                type: ShortAnswer
                width: 3em
                prepended_text: "$"
                hint: Blank with prepended text
                correct_answer:
                - type: float
                  value: 1
                  rtol: 0.00001
                - <plain> "1"

            blank4:
                type: ShortAnswer
                width: 3em
                appended_text: "%"
                hint: Blank with appended text
                correct_answer:
                - type: float
                  value: 5
                  rtol: 0.00001
                - <plain> "5"

            blank5:
                type: ShortAnswer
                width: 6em
                prepended_text: "("
                appended_text: ")"
                required: True
                hint: Blank with both prepended and appended text
                correct_answer:
                - <plain> BAR
                - <plain>bar
```

The ``<img src="repo:images/classroom.jpeg">`` in the question block just failed conversion. However, if I use an extra ``markup_to_html`` for the returned value of the [``get_question``](https://github.com/inducer/relate/blob/master/course/page/inline.py#L795-L802) method, then it worked.
