### ISSUE TITLE
Bug: extracted page title

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#498]
Extracted page title should
1. be able to be started by characters like `[ ] ! `
1. strip html tags after converted from markdown, which prevent weird html title like `**Important**` and `<span>foo</span>`

**Comment by dzhuang** [comment]
For example, the following markup would fail

```yaml
type: Page
id: welcome

content: |

    # **Important**
    Don't be scared.

```
