### ISSUE TITLE
nan causes TextQuestion to grade question as correct

### ISSUE THREAD

**Issue by davis68** [inducer/relate#651]
I haven't investigated the root cause yet, but entering `nan` on a TextQuestion such as the following causes the question to evaluate as correct.

```
    type: TextQuestion
    id: quiz
    value: 1
    access_rules:
        add_permissions:
            - see_correctness
            - change_answer
    prompt: |
        # Enter a value

        Enter the number `5.0`.

    answers:
        - type: float
          value: 5.0
          rtol: 1e-2
```
