### ISSUE TITLE
ScannerError when parsing LaTeX

### ISSUE THREAD

**Issue by davis68** [inducer/relate#721]
The code

```
-
    type: InlineMultiQuestion
    id: python_types__aargh_type
    value: 1
    title: "Checkpoint:  Mathematical Type"
    prompt: |
        Here is a question.

    question: |

        | Number | Set        |
        | ------ | ---------- |
        | $1$    | [[blank0]] |

    answers:

        blank0:
            type: ChoicesAnswer
            choices:
            - '~CORRECT~ $\mathbb{N}$'
            - '$\mathbb{Z}$'
            - '$\mathbb{Q}$'
            - '$\mathbb{R}$'
            - '$\mathbb{C}$'
```

yields the error

```
ValidationError: flows/lesson02__python_types.yml: ScannerError: while scanning a double-quoted scalar in "", line 551, column 19: - "ℕ" ^ found unknown escape character 'm' in "", line 551, column 22: - "ℕ" ^
```

For the time being, I will workaround by using blackboard bold Unicode instead of LaTeX, since \m is getting parsed wrong by PyYAML.
