### ISSUE TITLE
course validation text unhelpful

### ISSUE THREAD

**Issue by KlavsKlavsen** [inducer/relate#911]
When trying to add my course, I get:
answer 1: matcher string does not have expected format 

```
     -
         type: TextQuestion
         id: carlogic
         value: 1
         prompt: |
 
           # question 1
 
           this is a test
 
           Statement: is this a test?
           Is this: True, False or Insufficient information ?
 
         answers:
           - ~CORRECT~ True
           - False
           - Insufficient information
```
I have also tried ```<plain> True``` and same plain in front of the others - with no diff. outcome.

Where can I see the regex being tested on the answer - so I can figure out whats actually wrong? I have only found examples in relate-sample project - no docs about how to use CORRECT other than that.

The error message isn't helping me figure out whats wrong here :)
